[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools (>=70.1.0, <83.0)",
    "cmake (>=3.24, <4.0)",
    "jupyterlab (>=3.0.6, <3.6.0)",
    "conan (>=2.4.1, <3.0)",
    "cython ~= 3.0.10",
    "numpy < 3.0"
]
